// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LessCompiler
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "5ac1b994-61c2-4d5c-ab54-3c64f095a843";
        public const string guidAutoLoadString = "214a804c-9787-4ce6-bc4b-d4691dd46d2b";
        public const string guidPackageCmdSetString = "e9baa158-19eb-488b-93a6-9f305e55a422";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidAutoLoad = new Guid(guidAutoLoadString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ContextMenuGroup = 0x0001;
        public const int cmdEnabled = 0x1000;
    }
}
