// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LessCompiler
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "5ac1b994-61c2-4d5c-ab54-3c64f095a843";
        public const string guidInstallerPackageString = "a4aab915-6143-4ac5-b899-1bd64f6fd4c3";
        public const string guidPackageCmdSetString = "e26be7ce-2c0c-4810-b1fe-27f364e2811a";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidInstallerPackage = new Guid(guidInstallerPackageString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ReCompileAll = 0x1000;
    }
}
